sudo: required

language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry install --no-root

script:
  - bash ./scripts/test.sh
