os: linux

dist: focal

language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"

addons:
  postgresql: "13.1"

services:
  - postgresql

before_script:
  - psql -c 'create database codetutor;' -U postgres
install:
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry install --no-root

script:
  - bash ./scripts/test.sh
