image: python:3.9

pipelines:
  default:
    - parallel:
      - step:
          name: Test
          caches:
            - pip
          script:
            - pip install poetry
            - poetry config virtualenvs.create false
            - poetry install --no-root
            - poetry run pytest
      - step:
          name: Lint
          script:
            - flake8 . --extend-exclude=dist,build --show-source --statistics
            - black .
            - isort --color -n .