image: python:3.9 # Use python 3.9

pipelines:
  default:
    - step:
        name: Lint
        script:
          - pip install poetry
          - poetry config virtualenvs.create false
          - poetry install --no-root
          - poetry run flake8 src/ --extend-exclude=dist,build --show-source --statistics --max-line-length 120
          - poetry run black .
          - poetry run isort --color -n .
