image: python:3.9 # Use python 3.9

pipelines:
  default:
    - step:
        name: Virtualenv
        script:
          - pip install poetry
          - poetry config virtualenvs.create false
          - poetry install --no-root
    - step:
        name: Lint
        script:
          - poetry run flake8 . --extend-exclude=dist,build --show-source --statistics
          - poetry run black .
          - poetry run isort --color -n .
