image: python:3.9 # Use python 3.9

definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: "codetutor"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: ""

pipelines:
  default:
    - parallel:
        - step:
            name: Lint
            script:
              - pip install poetry
              - poetry config virtualenvs.create false
              - poetry install --no-root
              - poetry run flake8 src/ --extend-exclude=dist,build --show-source --statistics --max-line-length 120
              - poetry run black .
              - poetry run isort --color -n src/
        - step:
            name: Test
            services:
              - postgres
            script:
              - apt-get update && apt-get install -y postgresql-client
              - pip install poetry
              - poetry config virtualenvs.create false
              - poetry install --no-root
              - psql -c 'drop database if exists codetutor;' -U postgres
              - psql -c 'create database codetutor;' -U postgres
              - TEST=true bash ./scripts/test.sh
